const palabras = [
  "pizza", "hamburguesa", "taco", "ensalada", "sushi", "empanada", "asado", "pasta", "helado", "pan",
  "perro", "gato", "elefante", "tigre", "leon", "jirafa", "mono", "oso", "zorro", "pinguino",
  "rojo", "azul", "verde", "amarillo", "naranja", "violeta", "rosa", "negro", "blanco", "gris",
  "argentina", "brasil", "espana", "mexico", "italia", "francia", "japon", "china", "alemania", "canada",
  "manzana", "banana", "uva", "pera", "sandia", "melon", "frutilla", "kiwi", "mango", "futbol",
  "basquet", "tenis", "natacion", "boxeo", "rugby", "ciclismo", "golf", "voley", "esqui", "doctor",
  "maestro", "ingeniero", "bombero", "policia", "abogado", "panadero", "actor", "disenador", "mecanico", "camisa",
  "pantalon", "zapato", "vestido", "gorra", "abrigo", "bufanda", "remera", "falda", "guantes", "auto",
  "bicicleta", "tren", "avion", "barco", "subte", "moto", "camion", "colectivo", "patineta", "computadora",
  "telefono", "internet", "robot", "pantalla", "teclado", "impresora", "tablet", "auriculares", "consola",
  "libro", "mesa", "silla", "cama", "puerta", "ventana", "lapiz", "papel", "reloj", "espejo",
  "sol", "luna", "estrella", "nube", "lluvia", "viento", "calor", "frio", "nieve", "rayo",
  "rio", "mar", "montana", "bosque", "campo", "playa", "desierto", "isla", "ciudad", "pueblo",
  "casa", "edificio", "plaza", "parque", "escuela", "hospital", "tienda", "restaurante", "cine", "museo",
  "musica", "arte", "danza", "teatro", "poesia", "pintura", "escultura", "fotografia", "cine", "lectura",
  "escritura", "viaje", "aventura", "exploracion", "descubrimiento", "aprendizaje", "ensenanza", "conocimiento", "sabiduria", "creatividad",
  "imaginacion", "sueno", "realidad", "verdad", "mentira", "paz", "guerra", "amor", "odio", "alegria",
  "tristeza", "miedo", "valor", "coraje", "esperanza", "fe", "amistad", "familia", "comunidad", "sociedad",
  "justicia", "libertad", "derecho", "deber", "etica", "moral", "ley", "regla", "orden", "caos",
  "energia", "fuerza", "velocidad", "tiempo", "espacio", "universo", "planeta", "galaxia", "cometa", "asteroide",
  "volcan", "terremoto", "tsunami", "inundacion", "sequia", "incendio", "tormenta", "huracan", "tornado", "erupcion",
  "enfermedad", "salud", "medicina", "hospital", "terapia", "vacuna", "virus", "bacteria", "microbio", "celula",
  "ADN", "gen", "evolucion", "especie", "naturaleza", "ecologia", "ambiente", "contaminacion", "reciclaje", "energia",
  "electricidad", "magnetismo", "gravedad", "luz", "sonido", "calor", "frio", "quimica", "fisica", "biologia",
  "matematica", "geometria", "algebra", "calculo", "estadistica", "logica", "filosofia", "historia", "geografia", "economia",
  "politica", "gobierno", "democracia", "monarquia", "dictadura", "revolucion", "protesta", "eleccion", "voto", "ciudadano",
  "poblacion", "cultura", "tradicion", "costumbre", "idioma", "lenguaje", "comunicacion", "dialogo", "debate", "noticia",
  "periodico", "revista", "radio", "television", "cine", "documental", "ficcion", "novela", "cuento", "poema",
  "cancion", "melodia", "ritmo", "instrumento", "concierto", "festival", "fiesta", "celebracion", "vacaciones", "descanso",
  "trabajo", "empleo", "carrera", "oficina", "empresa", "negocio", "mercado", "dinero", "banco", "inversion",
  "riqueza", "pobreza", "hambre", "sed", "refugio", "hogar", "refugiado", "migrante", "frontera", "pasaporte",
  "aduanas", "seguridad", "peligro", "riesgo", "accidente", "desastre", "emergencia", "ayuda", "rescate", "voluntario",
  "deporte", "juego", "competencia", "victoria", "derrota", "medalla", "copa", "trofeo", "entrenamiento", "disciplina",
  "nutricion", "ejercicio", "dieta", "cocina", "receta", "ingrediente", "sabor", "aroma", "textura", "bebida",
  "agua", "leche", "jugo", "cafe", "te", "cerveza", "vino", "gaseosa", "postre", "galleta",
  "panal", "cereal", "fruto", "vegetal", "carne", "pescado", "huevo", "queso", "mantequilla", "aceite",
  "sal", "azucar", "miel", "especias", "hierbas", "condimento", "sopa", "guiso", "estofado", "asado",
  "fritura", "horneado", "cocido", "crudo", "fresco", "seco", "dulce", "salado", "amargo", "acido",
  "picante", "caliente", "frio", "tibio", "ligero", "pesado", "suave", "duro", "liquido", "solido",
  "gaseoso", "vapor", "humo", "ceniza", "polvo", "arena", "piedra", "madera", "metal", "plastico",
  "vidrio", "papel", "tela", "cuero", "goma", "lana", "algodon", "seda", "ceramica", "cemento",
  "tierra", "barro", "lodo", "roca", "cristal", "diamante", "oro", "plata", "bronce", "cobre",
  "hierro", "acero", "aluminio", "carbon", "petroleo", "gas", "urani", "radio", "plutonio", "mercurio",
  "venus", "marte", "jupiter", "saturno", "urano", "neptuno", "pluton", "solsticio", "equinoccio", "eclipse",
  "constelacion", "galaxia", "nebulosa", "agujero", "negro", "cuasar", "pulsar", "supernova", "bigbang", "cosmos"
];

export default palabras;
